# Generated by Django 5.1.7 on 2025-08-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("organizations", "0003_enrollment_date_first_attendance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email__isnull", False)),
                fields=("organization", "email"),
                name="unique_email_per_organization_when_not_null",
            ),
        ),
    ]
