# Generated by Django 5.1.7 on 2025-09-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_fix_student_email_unique"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="studentprofile",
            name="unique_email_per_organization_when_not_null",
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
