# Generated by Django 5.1.7 on 2025-09-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_remove_studentprofile_unique_email_per_organization_when_not_null_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="must_change_password",
            field=models.BooleanField(
                default=False, help_text="Forces user to change password on next login"
            ),
        ),
    ]
