# Generated by Django 4.2.23 on 2026-02-28 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy_contents', '0001_initial'),
        ('organizations', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingvideo',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.batch'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='target_students',
            field=models.ManyToManyField(blank=True, related_name='assigned_videos', to='accounts.studentprofile'),
        ),
    ]
