# Generated by Django 4.2.23 on 2026-04-03 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('academy_contents', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingvideo',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='trainingvideo',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='trainingvideo',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='trainingvideo',
            name='target_students',
        ),
        migrations.RemoveField(
            model_name='trainingvideo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='trainingvideo',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='trainingvideo',
            name='video_file',
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='is_from_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='student_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_videos', to='accounts.studentprofile'),
        ),
    ]
