# Generated by Django 4.2.30 on 2026-04-29 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('academy_contents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingvideo',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.batch'),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.branch'),
        ),
    ]
