# Generated by Django 4.2.23 on 2026-02-28 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_file', models.FileField(upload_to='player_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.batch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.branch')),
                ('students', models.ManyToManyField(related_name='reports', to='accounts.studentprofile')),
            ],
        ),
    ]
