# Generated by Django 4.2.23 on 2025-10-05 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('schedule_details', models.JSONField(default=dict, help_text="e.g., {'days': ['Mon', 'Wed'], 'start_time': '18:00', 'end_time': '19:00'}")),
                ('max_students', models.IntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='sport_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full legal name of the organization/academy', max_length=255)),
                ('academy_name', models.CharField(help_text='Commonly used display name', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='academy_logos/')),
                ('location', models.TextField(blank=True, help_text='Full physical address of the primary location')),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('slug', models.SlugField(help_text="Unique identifier for URL, e.g., 'elite-tennis'", max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription_plan', models.CharField(choices=[('FREE_TRIAL', 'Free Trial'), ('BASIC', 'Basic'), ('PREMIUM', 'Premium')], default='FREE_TRIAL', max_length=50)),
                ('subscription_end_date', models.DateField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('sports_offered', models.ManyToManyField(blank=True, related_name='organizations', to='organizations.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_type', models.CharField(choices=[('SESSION_BASED', 'Session Based'), ('DURATION_BASED', 'Duration Based')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_sessions', models.IntegerField(blank=True, null=True)),
                ('sessions_attended', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('enrollment_started', models.BooleanField(default=False)),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
                ('date_first_attendance', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='organizations.batch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='organizations.organization')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='batch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='batch',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='organizations.sport'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_session_deducted', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_attendances', to='organizations.batch')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='organizations.enrollment')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='accounts.studentprofile')),
            ],
            options={
                'unique_together': {('enrollment', 'date')},
            },
        ),
    ]
