# Generated by Django 5.2 on 2025-10-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='fee_per_session',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='payment_policy',
            field=models.CharField(choices=[('PRE_PAID', 'Pre-paid'), ('POST_PAID', 'Post-paid')], default='POST_PAID', max_length=20),
        ),
    ]
