# Generated by Django 5.2.4 on 2025-07-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="sports_offered",
            field=models.ManyToManyField(
                blank=True, related_name="organizations", to="organizations.sport"
            ),
        ),
    ]
