# Generated by Django 5.1.7 on 2025-08-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organization_sports_offered"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="date_first_attendance",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="enrollment_started",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
