# Generated by Django 5.1.1 on 2026-02-21 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_enrollment_validation_error_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date the match was played')),
                ('format', models.CharField(choices=[('SINGLES', 'Singles'), ('DOUBLES', 'Doubles')], max_length=10)),
                ('importance', models.CharField(choices=[('CASUAL', 'Casual'), ('LEAGUE', 'League'), ('TOURNAMENT', 'Tournament')], default='CASUAL', max_length=15)),
                ('participants', models.JSONField(help_text='List of participant user IDs, ordered: [winner_side..., loser_side...]')),
                ('score', models.JSONField(help_text='Match score as flexible JSON')),
                ('dedup_hash', models.CharField(help_text='Collision-resistant hash for duplicate detection', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending confirmation'), ('VALIDATED', 'Validated'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('REJECTED', 'Rejected'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=15)),
                ('validated', models.BooleanField(default=False, help_text='True once match is confirmed and ready for rating processing')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual submission'), ('AUTO', 'Auto-generated'), ('IMPORT', 'Bulk import')], default='MANUAL', max_length=10)),
                ('rolled_back', models.BooleanField(default=False)),
                ('rollback_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_matches', to='organizations.organization')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_matches', to='organizations.sport')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rating Match',
                'verbose_name_plural': 'Rating Matches',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RatingAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('SINGLES', 'Singles'), ('DOUBLES', 'Doubles')], default='SINGLES', max_length=10)),
                ('old_rating', models.DecimalField(decimal_places=3, max_digits=7)),
                ('new_rating', models.DecimalField(decimal_places=3, max_digits=7)),
                ('delta', models.DecimalField(decimal_places=3, help_text='new_rating - old_rating (positive = improvement)', max_digits=7)),
                ('method', models.CharField(choices=[('LIVE', 'Live (per-match async)'), ('BATCH', 'Batch recompute'), ('ROLLBACK', 'Rollback')], default='LIVE', max_length=10)),
                ('note', models.TextField(blank=True, help_text='Human-readable explanation or batch run ID')),
                ('rolled_back', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(blank=True, help_text='Null for manual admin adjustments', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='ratings.ratingmatch')),
            ],
            options={
                'verbose_name': 'Rating Audit Entry',
                'verbose_name_plural': 'Rating Audit Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerRatingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dupr_rating_singles', models.DecimalField(decimal_places=3, default=4.0, help_text='Current DUPR singles rating (2.000 – 8.000)', max_digits=7)),
                ('dupr_rating_doubles', models.DecimalField(decimal_places=3, default=4.0, help_text='Current DUPR doubles rating (2.000 – 8.000)', max_digits=7)),
                ('matches_played_singles', models.PositiveIntegerField(default=0)),
                ('matches_played_doubles', models.PositiveIntegerField(default=0)),
                ('reliability', models.PositiveSmallIntegerField(default=0, help_text='0–100; provisional when < 10 matches; 100 = fully established')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_ratings', to='organizations.organization')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_ratings', to='organizations.sport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Player Rating Profile',
                'verbose_name_plural': 'Player Rating Profiles',
                'indexes': [models.Index(fields=['organization', 'sport'], name='ratings_pla_organiz_dece38_idx'), models.Index(fields=['user', 'sport'], name='ratings_pla_user_id_34b9dc_idx')],
                'unique_together': {('user', 'sport', 'organization')},
            },
        ),
        migrations.AddIndex(
            model_name='ratingmatch',
            index=models.Index(fields=['organization', 'sport', 'status'], name='ratings_rat_organiz_0d5fda_idx'),
        ),
        migrations.AddIndex(
            model_name='ratingmatch',
            index=models.Index(fields=['dedup_hash'], name='ratings_rat_dedup_h_77ce70_idx'),
        ),
        migrations.AddIndex(
            model_name='ratingmatch',
            index=models.Index(fields=['date'], name='ratings_rat_date_fa315a_idx'),
        ),
        migrations.AddIndex(
            model_name='ratingaudit',
            index=models.Index(fields=['player', '-created_at'], name='ratings_rat_player__786b8b_idx'),
        ),
        migrations.AddIndex(
            model_name='ratingaudit',
            index=models.Index(fields=['match'], name='ratings_rat_match_i_b4133e_idx'),
        ),
    ]
