# Generated by Django 5.1.1 on 2026-02-28 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingmatch',
            name='deadline_at',
            field=models.DateTimeField(blank=True, help_text='Deadline for opponent action', null=True),
        ),
        migrations.AddField(
            model_name='ratingmatch',
            name='evidence_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ratingmatch',
            name='fraud_score',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='0.000 to 1.000 (IsolationForest anomaly score)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='ratingmatch',
            name='is_processed_for_rating',
            field=models.BooleanField(default=False, help_text='Flag indicating Celery worker has applied the rating math'),
        ),
        migrations.AddField(
            model_name='ratingmatch',
            name='opponent_score',
            field=models.JSONField(blank=True, help_text='Match score submitted by opponent if differing', null=True),
        ),
        migrations.AddField(
            model_name='ratingmatch',
            name='resolved_score',
            field=models.JSONField(blank=True, help_text='The final, authorized score used for rating calculation', null=True),
        ),
        migrations.AlterField(
            model_name='playerratingprofile',
            name='reliability',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='0–100; baseline 50.00. Dictates voting power in disputes.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='ratingmatch',
            name='score',
            field=models.JSONField(help_text='Match score submitted by reporter'),
        ),
        migrations.AlterField(
            model_name='ratingmatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending opponent confirmation'), ('CONFIRMED', 'Confirmed exactly'), ('DISPUTED', 'Major dispute (Admin Review)'), ('AUTO_RESOLVED', 'Auto-resolved (Weighted math)'), ('ADMIN_RESOLVED', 'Admin resolved'), ('REJECTED', 'Rejected/Nullified')], default='PENDING', max_length=15),
        ),
        migrations.CreateModel(
            name='MatchAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('PENDING', 'Pending opponent confirmation'), ('CONFIRMED', 'Confirmed exactly'), ('DISPUTED', 'Major dispute (Admin Review)'), ('AUTO_RESOLVED', 'Auto-resolved (Weighted math)'), ('ADMIN_RESOLVED', 'Admin resolved'), ('REJECTED', 'Rejected/Nullified')], max_length=20)),
                ('new_status', models.CharField(choices=[('PENDING', 'Pending opponent confirmation'), ('CONFIRMED', 'Confirmed exactly'), ('DISPUTED', 'Major dispute (Admin Review)'), ('AUTO_RESOLVED', 'Auto-resolved (Weighted math)'), ('ADMIN_RESOLVED', 'Admin resolved'), ('REJECTED', 'Rejected/Nullified')], max_length=20)),
                ('action_type', models.CharField(help_text='e.g. SUBMITTED, COUNTER_SUBMITTED, AUTO_RESOLVED, FRAUD_FLAGGED, ADMIN_RESOLVED', max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered this change (can be null for system tasks)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_audits', to='ratings.ratingmatch')),
            ],
            options={
                'verbose_name': 'Match Audit Trail',
                'verbose_name_plural': 'Match Audit Trails',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['match'], name='ratings_mat_match_i_2c1ded_idx'), models.Index(fields=['action_type'], name='ratings_mat_action__c9becf_idx')],
            },
        ),
    ]
