# Generated by Django 5.1.1 on 2026-02-21 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetransaction',
            name='paid_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the payment was marked as paid', null=True),
        ),
        migrations.AlterField(
            model_name='feetransaction',
            name='transaction_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
