# Generated by Django 4.2.23 on 2026-03-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_generalexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feetransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Net Banking')], default='cash', max_length=20),
        ),
    ]
