# Generated by Django 4.2.23 on 2026-02-28 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('specialization', models.CharField(blank=True, help_text='e.g. Tennis, Yoga, etc.', max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='coach_profiles/')),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='organizations.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoachAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.batch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.branch')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='coaches.coachprofile')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.sport')),
            ],
            options={
                'unique_together': {('coach', 'batch')},
            },
        ),
    ]
