# Generated by Django 5.1.1 on 2026-02-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='specialization',
            field=models.CharField(blank=True, help_text='e.g. Tennis, Yoga, etc.', max_length=100),
        ),
    ]
